"""
Configuration module for VAPI Batch Calling System
"""

from .settings import (
    VAPI_API_KEY,
    DIRECT_BILL_1ST_REMAINDER_ASSISTANT_ID,
    DIRECT_BILL_2ND_REMAINDER_ASSISTANT_ID,
    MORTGAGE_BILL_1ST_REMAINDER_ASSISTANT_ID,
    MORTGAGE_BILL_2ND_REMAINDER_ASSISTANT_ID,
    CANCELLATION_1ST_REMINDER_ASSISTANT_ID,
    CANCELLATION_2ND_REMINDER_ASSISTANT_ID,
    CANCELLATION_3RD_REMINDER_ASSISTANT_ID,
    COMPANY_PHONE_NUMBER_ID,
    SMARTSHEET_ACCESS_TOKEN,
    CANCELLATION_SHEET_ID,
    CANCELLATION_DEV_SHEET_ID,
    CANCELLATION_DEV_2_SHEET_ID,
    TEST_CUSTOMER_PHONE
)

__all__ = [
    'VAPI_API_KEY',
    'DIRECT_BILL_1ST_REMAINDER_ASSISTANT_ID',
    'DIRECT_BILL_2ND_REMAINDER_ASSISTANT_ID',
    'MORTGAGE_BILL_1ST_REMAINDER_ASSISTANT_ID',
    'MORTGAGE_BILL_2ND_REMAINDER_ASSISTANT_ID',
    'CANCELLATION_1ST_REMINDER_ASSISTANT_ID',
    'CANCELLATION_2ND_REMINDER_ASSISTANT_ID',
    'CANCELLATION_3RD_REMINDER_ASSISTANT_ID',
    'COMPANY_PHONE_NUMBER_ID',
    'SMARTSHEET_ACCESS_TOKEN',
    'CANCELLATION_SHEET_ID',
    'CANCELLATION_DEV_SHEET_ID',
    'CANCELLATION_DEV_2_SHEET_ID',
    'TEST_CUSTOMER_PHONE'
]
